import { tradingViewSymbolFromYahoo } from "@/lib/tradingview";
import { normalizeEquityTicker } from "@/lib/ticker-normalize";

export type IndianSectorStock = {
  ticker: string;
  name: string;
};

export type IndianSector = {
  id: string;
  label: string;
  yahooSymbol: string;
  isBenchmark?: boolean;
  stocks: IndianSectorStock[];
};

export const INDIAN_SECTORS: IndianSector[] = [
  {
    id: "nifty-50",
    label: "Nifty 50",
    yahooSymbol: "^NSEI",
    isBenchmark: true,
    stocks: [],
  },
  {
    id: "bank",
    label: "Bank",
    yahooSymbol: "^NSEBANK",
    stocks: [
      { ticker: "HDFCBANK", name: "HDFC Bank" },
      { ticker: "ICICIBANK", name: "ICICI Bank" },
      { ticker: "SBIN", name: "State Bank of India" },
      { ticker: "AXISBANK", name: "Axis Bank" },
      { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank" },
      { ticker: "INDUSINDBK", name: "IndusInd Bank" },
      { ticker: "BANKBARODA", name: "Bank of Baroda" },
      { ticker: "FEDERALBNK", name: "Federal Bank" },
      { ticker: "IDFCFIRSTB", name: "IDFC First Bank" },
      { ticker: "PNB", name: "Punjab National Bank" },
      { ticker: "AUBANK", name: "AU Small Finance Bank" },
      { ticker: "CANBK", name: "Canara Bank" },
    ],
  },
  {
    id: "it",
    label: "IT",
    yahooSymbol: "^CNXIT",
    stocks: [
      { ticker: "TCS", name: "Tata Consultancy Services" },
      { ticker: "INFY", name: "Infosys" },
      { ticker: "HCLTECH", name: "HCL Technologies" },
      { ticker: "WIPRO", name: "Wipro" },
      { ticker: "TECHM", name: "Tech Mahindra" },
      { ticker: "LTIM", name: "LTIMindtree" },
      { ticker: "PERSISTENT", name: "Persistent Systems" },
      { ticker: "COFORGE", name: "Coforge" },
      { ticker: "MPHASIS", name: "Mphasis" },
      { ticker: "LTTS", name: "L&T Technology Services" },
    ],
  },
  {
    id: "pharma",
    label: "Pharma",
    yahooSymbol: "^CNXPHARMA",
    stocks: [
      { ticker: "SUNPHARMA", name: "Sun Pharma" },
      { ticker: "DIVISLAB", name: "Divi's Laboratories" },
      { ticker: "CIPLA", name: "Cipla" },
      { ticker: "DRREDDY", name: "Dr. Reddy's" },
      { ticker: "MANKIND", name: "Mankind Pharma" },
      { ticker: "LUPIN", name: "Lupin" },
      { ticker: "AUROPHARMA", name: "Aurobindo Pharma" },
      { ticker: "TORNTPHARM", name: "Torrent Pharma" },
      { ticker: "ALKEM", name: "Alkem Laboratories" },
      { ticker: "ZYDUSLIFE", name: "Zydus Lifesciences" },
      { ticker: "GLENMARK", name: "Glenmark" },
      { ticker: "BIOCON", name: "Biocon" },
      { ticker: "LAURUSLABS", name: "Laurus Labs" },
      { ticker: "IPCALAB", name: "IPCA Laboratories" },
    ],
  },
  {
    id: "auto",
    label: "Auto",
    yahooSymbol: "^CNXAUTO",
    stocks: [
      { ticker: "MARUTI", name: "Maruti Suzuki" },
      { ticker: "TATAMOTORS", name: "Tata Motors" },
      { ticker: "M&M", name: "Mahindra & Mahindra" },
      { ticker: "BAJAJ-AUTO", name: "Bajaj Auto" },
      { ticker: "EICHERMOT", name: "Eicher Motors" },
      { ticker: "HEROMOTOCO", name: "Hero MotoCorp" },
      { ticker: "TVSMOTOR", name: "TVS Motor" },
      { ticker: "BHARATFORG", name: "Bharat Forge" },
      { ticker: "MOTHERSON", name: "Samvardhana Motherson" },
      { ticker: "BOSCHLTD", name: "Bosch" },
      { ticker: "ASHOKLEY", name: "Ashok Leyland" },
      { ticker: "TIINDIA", name: "Tube Investments" },
      { ticker: "BALKRISIND", name: "Balkrishna Industries" },
      { ticker: "MRF", name: "MRF" },
    ],
  },
  {
    id: "fmcg",
    label: "FMCG",
    yahooSymbol: "^CNXFMCG",
    stocks: [
      { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
      { ticker: "ITC", name: "ITC" },
      { ticker: "NESTLEIND", name: "Nestle India" },
      { ticker: "BRITANNIA", name: "Britannia" },
      { ticker: "TATACONSUM", name: "Tata Consumer" },
      { ticker: "DABUR", name: "Dabur" },
      { ticker: "GODREJCP", name: "Godrej Consumer" },
      { ticker: "MARICO", name: "Marico" },
      { ticker: "COLPAL", name: "Colgate-Palmolive" },
      { ticker: "UBL", name: "United Breweries" },
      { ticker: "VBL", name: "Varun Beverages" },
      { ticker: "RADICO", name: "Radico Khaitan" },
      { ticker: "TRENT", name: "Trent" },
      { ticker: "UNITDSPR", name: "United Spirits" },
    ],
  },
  {
    id: "metal",
    label: "Metal",
    yahooSymbol: "^CNXMETAL",
    stocks: [
      { ticker: "TATASTEEL", name: "Tata Steel" },
      { ticker: "JSWSTEEL", name: "JSW Steel" },
      { ticker: "HINDALCO", name: "Hindalco" },
      { ticker: "VEDL", name: "Vedanta" },
      { ticker: "JINDALSTEL", name: "Jindal Steel" },
      { ticker: "ADANIENT", name: "Adani Enterprises" },
      { ticker: "HINDZINC", name: "Hindustan Zinc" },
      { ticker: "NATIONALUM", name: "NALCO" },
      { ticker: "SAIL", name: "SAIL" },
      { ticker: "NMDC", name: "NMDC" },
      { ticker: "APLAPOLLO", name: "APL Apollo" },
      { ticker: "WELCORP", name: "Welspun Corp" },
    ],
  },
  {
    id: "cement",
    label: "Cement",
    yahooSymbol: "NIFTY_CEMENT.NS",
    stocks: [
      { ticker: "ULTRACEMCO", name: "UltraTech Cement" },
      { ticker: "AMBUJACEM", name: "Ambuja Cements" },
      { ticker: "SHREECEM", name: "Shree Cement" },
      { ticker: "DALBHARAT", name: "Dalmia Bharat" },
      { ticker: "JKCEMENT", name: "JK Cement" },
      { ticker: "ACC", name: "ACC" },
      { ticker: "RAMCOCEM", name: "The Ramco Cements" },
      { ticker: "NUVOCO", name: "Nuvoco Vistas" },
      { ticker: "JKLAKSHMI", name: "JK Lakshmi Cement" },
      { ticker: "BIRLACORPN", name: "Birla Corporation" },
    ],
  },
  {
    id: "realty",
    label: "Realty",
    yahooSymbol: "^CNXREALTY",
    stocks: [
      { ticker: "DLF", name: "DLF" },
      { ticker: "GODREJPROP", name: "Godrej Properties" },
      { ticker: "OBEROIRLTY", name: "Oberoi Realty" },
      { ticker: "PRESTIGE", name: "Prestige Estates" },
      { ticker: "PHOENIXLTD", name: "Phoenix Mills" },
      { ticker: "BRIGADE", name: "Brigade Enterprises" },
      { ticker: "SOBHA", name: "Sobha" },
      { ticker: "LODHA", name: "Macrotech Developers" },
    ],
  },
  {
    id: "housing",
    label: "Housing",
    yahooSymbol: "NIFTY_HOUSING.NS",
    stocks: [
      { ticker: "DLF", name: "DLF" },
      { ticker: "LODHA", name: "Macrotech Developers" },
      { ticker: "ULTRACEMCO", name: "UltraTech Cement" },
      { ticker: "ASIANPAINT", name: "Asian Paints" },
      { ticker: "HAVELLS", name: "Havells" },
      { ticker: "LICHSGFIN", name: "LIC Housing Finance" },
      { ticker: "POLYCAB", name: "Polycab" },
      { ticker: "ASTRAL", name: "Astral" },
      { ticker: "GODREJPROP", name: "Godrej Properties" },
      { ticker: "PRESTIGE", name: "Prestige Estates" },
    ],
  },
  {
    id: "energy",
    label: "Energy",
    yahooSymbol: "^CNXENERGY",
    stocks: [
      { ticker: "RELIANCE", name: "Reliance Industries" },
      { ticker: "ONGC", name: "ONGC" },
      { ticker: "NTPC", name: "NTPC" },
      { ticker: "POWERGRID", name: "Power Grid" },
      { ticker: "COALINDIA", name: "Coal India" },
      { ticker: "IOC", name: "Indian Oil" },
      { ticker: "BPCL", name: "BPCL" },
      { ticker: "ADANIGREEN", name: "Adani Green" },
      { ticker: "TATAPOWER", name: "Tata Power" },
      { ticker: "ADANIPOWER", name: "Adani Power" },
      { ticker: "GAIL", name: "GAIL" },
      { ticker: "HINDPETRO", name: "Hindustan Petroleum" },
    ],
  },
  {
    id: "power",
    label: "Power",
    yahooSymbol: "NIFTY_POWER.NS",
    stocks: [
      { ticker: "NTPC", name: "NTPC" },
      { ticker: "POWERGRID", name: "Power Grid" },
      { ticker: "TATAPOWER", name: "Tata Power" },
      { ticker: "ADANIPOWER", name: "Adani Power" },
      { ticker: "ADANIGREEN", name: "Adani Green" },
      { ticker: "JSWENERGY", name: "JSW Energy" },
      { ticker: "TORNTPOWER", name: "Torrent Power" },
      { ticker: "NHPC", name: "NHPC" },
      { ticker: "SJVN", name: "SJVN" },
      { ticker: "ADANIENSOL", name: "Adani Energy Solutions" },
      { ticker: "CESC", name: "CESC" },
      { ticker: "NLCINDIA", name: "NLC India" },
    ],
  },
  {
    id: "financials",
    label: "Financial Services",
    yahooSymbol: "NIFTY_FIN_SERVICE.NS",
    stocks: [
      { ticker: "HDFCBANK", name: "HDFC Bank" },
      { ticker: "ICICIBANK", name: "ICICI Bank" },
      { ticker: "SBIN", name: "State Bank of India" },
      { ticker: "BAJFINANCE", name: "Bajaj Finance" },
      { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank" },
      { ticker: "AXISBANK", name: "Axis Bank" },
      { ticker: "BAJAJFINSV", name: "Bajaj Finserv" },
      { ticker: "HDFCLIFE", name: "HDFC Life" },
      { ticker: "SBILIFE", name: "SBI Life" },
      { ticker: "PFC", name: "Power Finance" },
      { ticker: "RECLTD", name: "REC" },
      { ticker: "CHOLAFIN", name: "Cholamandalam" },
      { ticker: "SHRIRAMFIN", name: "Shriram Finance" },
      { ticker: "HDFCAMC", name: "HDFC AMC" },
      { ticker: "MUTHOOTFIN", name: "Muthoot Finance" },
      { ticker: "ICICIPRULI", name: "ICICI Prudential Life" },
    ],
  },
  {
    id: "nbfc",
    label: "NBFC",
    yahooSymbol: "NIFTY_NBFC.NS",
    stocks: [
      { ticker: "BAJFINANCE", name: "Bajaj Finance" },
      { ticker: "BAJAJFINSV", name: "Bajaj Finserv" },
      { ticker: "CHOLAFIN", name: "Cholamandalam" },
      { ticker: "SHRIRAMFIN", name: "Shriram Finance" },
      { ticker: "MUTHOOTFIN", name: "Muthoot Finance" },
      { ticker: "PFC", name: "Power Finance" },
      { ticker: "RECLTD", name: "REC" },
      { ticker: "SBICARD", name: "SBI Cards" },
      { ticker: "M&MFIN", name: "M&M Financial" },
      { ticker: "POONAWALLA", name: "Poonawalla Fincorp" },
      { ticker: "MANAPPURAM", name: "Manappuram Finance" },
      { ticker: "LTF", name: "L&T Finance" },
    ],
  },
  {
    id: "insurance",
    label: "Insurance",
    yahooSymbol: "NIFTY_INSURANCE.NS",
    stocks: [
      { ticker: "LICI", name: "LIC" },
      { ticker: "HDFCLIFE", name: "HDFC Life" },
      { ticker: "SBILIFE", name: "SBI Life" },
      { ticker: "ICICIPRULI", name: "ICICI Prudential Life" },
      { ticker: "ICICIGI", name: "ICICI Lombard" },
      { ticker: "GICRE", name: "GIC Re" },
      { ticker: "NIACL", name: "New India Assurance" },
      { ticker: "STARHEALTH", name: "Star Health" },
      { ticker: "GODIGIT", name: "Go Digit" },
      { ticker: "NIVABUPA", name: "Niva Bupa" },
    ],
  },
  {
    id: "housing-finance",
    label: "Housing Finance",
    yahooSymbol: "NIFTY_HOUSING_FINANCE.NS",
    stocks: [
      { ticker: "LICHSGFIN", name: "LIC Housing Finance" },
      { ticker: "CANFINHOME", name: "Can Fin Homes" },
      { ticker: "PNBHOUSING", name: "PNB Housing" },
      { ticker: "AAVAS", name: "Aavas Financiers" },
      { ticker: "HOMEFIRST", name: "Home First Finance" },
      { ticker: "APTUS", name: "Aptus Value Housing" },
      { ticker: "HUDCO", name: "HUDCO" },
      { ticker: "BAJFINANCE", name: "Bajaj Finance" },
      { ticker: "CHOLAFIN", name: "Cholamandalam" },
      { ticker: "HDFCBANK", name: "HDFC Bank" },
    ],
  },
  {
    id: "fin-ex-bank",
    label: "Financials Ex-Bank",
    yahooSymbol: "NIFTY_FINSRVEXBNK.NS",
    stocks: [
      { ticker: "BAJFINANCE", name: "Bajaj Finance" },
      { ticker: "BAJAJFINSV", name: "Bajaj Finserv" },
      { ticker: "LICI", name: "LIC" },
      { ticker: "HDFCLIFE", name: "HDFC Life" },
      { ticker: "SBILIFE", name: "SBI Life" },
      { ticker: "PFC", name: "Power Finance" },
      { ticker: "RECLTD", name: "REC" },
      { ticker: "CHOLAFIN", name: "Cholamandalam" },
      { ticker: "SHRIRAMFIN", name: "Shriram Finance" },
      { ticker: "HDFCAMC", name: "HDFC AMC" },
      { ticker: "ICICIGI", name: "ICICI Lombard" },
      { ticker: "SBICARD", name: "SBI Cards" },
    ],
  },
  {
    id: "psu-bank",
    label: "PSU Bank",
    yahooSymbol: "^CNXPSUBANK",
    stocks: [
      { ticker: "SBIN", name: "State Bank of India" },
      { ticker: "BANKBARODA", name: "Bank of Baroda" },
      { ticker: "PNB", name: "Punjab National Bank" },
      { ticker: "CANBK", name: "Canara Bank" },
      { ticker: "UNIONBANK", name: "Union Bank" },
      { ticker: "INDIANB", name: "Indian Bank" },
      { ticker: "BANKINDIA", name: "Bank of India" },
      { ticker: "MAHABANK", name: "Bank of Maharashtra" },
      { ticker: "IOB", name: "Indian Overseas Bank" },
      { ticker: "UCOBANK", name: "UCO Bank" },
    ],
  },
  {
    id: "private-bank",
    label: "Private Bank",
    yahooSymbol: "NIFTY_PVT_BANK.NS",
    stocks: [
      { ticker: "HDFCBANK", name: "HDFC Bank" },
      { ticker: "ICICIBANK", name: "ICICI Bank" },
      { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank" },
      { ticker: "AXISBANK", name: "Axis Bank" },
      { ticker: "INDUSINDBK", name: "IndusInd Bank" },
      { ticker: "FEDERALBNK", name: "Federal Bank" },
      { ticker: "IDFCFIRSTB", name: "IDFC First Bank" },
      { ticker: "RBLBANK", name: "RBL Bank" },
      { ticker: "BANDHANBNK", name: "Bandhan Bank" },
      { ticker: "CUB", name: "City Union Bank" },
    ],
  },
  {
    id: "media",
    label: "Media",
    yahooSymbol: "^CNXMEDIA",
    stocks: [
      { ticker: "ZEEL", name: "Zee Entertainment" },
      { ticker: "SUNTV", name: "Sun TV Network" },
      { ticker: "PVRINOX", name: "PVR INOX" },
      { ticker: "NETWORK18", name: "Network18" },
      { ticker: "TVTODAY", name: "TV Today" },
      { ticker: "NAZARA", name: "Nazara Technologies" },
      { ticker: "TIPSMUSIC", name: "Tips Music" },
      { ticker: "SAREGAMA", name: "Saregama" },
    ],
  },
  {
    id: "infra",
    label: "Infrastructure",
    yahooSymbol: "^CNXINFRA",
    stocks: [
      { ticker: "LT", name: "Larsen & Toubro" },
      { ticker: "NTPC", name: "NTPC" },
      { ticker: "POWERGRID", name: "Power Grid" },
      { ticker: "ULTRACEMCO", name: "UltraTech Cement" },
      { ticker: "ADANIPORTS", name: "Adani Ports" },
      { ticker: "GRASIM", name: "Grasim" },
      { ticker: "TATAPOWER", name: "Tata Power" },
      { ticker: "SIEMENS", name: "Siemens" },
      { ticker: "ABB", name: "ABB India" },
      { ticker: "HAL", name: "Hindustan Aeronautics" },
      { ticker: "BEL", name: "Bharat Electronics" },
      { ticker: "BHEL", name: "BHEL" },
    ],
  },
  {
    id: "capital-goods",
    label: "Capital Goods",
    yahooSymbol: "NIFTY_CAPITAL_GOODS.NS",
    stocks: [
      { ticker: "LT", name: "Larsen & Toubro" },
      { ticker: "SIEMENS", name: "Siemens" },
      { ticker: "ABB", name: "ABB India" },
      { ticker: "CGPOWER", name: "CG Power" },
      { ticker: "CUMMINSIND", name: "Cummins India" },
      { ticker: "BHEL", name: "BHEL" },
      { ticker: "THERMAX", name: "Thermax" },
      { ticker: "HONAUT", name: "Honeywell Automation" },
      { ticker: "BEL", name: "Bharat Electronics" },
      { ticker: "HAL", name: "Hindustan Aeronautics" },
      { ticker: "POLYCAB", name: "Polycab" },
      { ticker: "KEI", name: "KEI Industries" },
    ],
  },
  {
    id: "construction",
    label: "Construction",
    yahooSymbol: "NIFTY_CONSTRUCTION.NS",
    stocks: [
      { ticker: "LT", name: "Larsen & Toubro" },
      { ticker: "RVNL", name: "Rail Vikas Nigam" },
      { ticker: "IRCON", name: "IRCON International" },
      { ticker: "NBCC", name: "NBCC" },
      { ticker: "NCC", name: "NCC" },
      { ticker: "KEC", name: "KEC International" },
      { ticker: "KPIL", name: "Kalpataru Projects" },
      { ticker: "PNCINFRA", name: "PNC Infratech" },
      { ticker: "GRINFRA", name: "G R Infraprojects" },
      { ticker: "HGINFRA", name: "H.G. Infra" },
    ],
  },
  {
    id: "healthcare",
    label: "Healthcare",
    yahooSymbol: "NIFTY_HEALTHCARE.NS",
    stocks: [
      { ticker: "SUNPHARMA", name: "Sun Pharma" },
      { ticker: "MAXHEALTH", name: "Max Healthcare" },
      { ticker: "APOLLOHOSP", name: "Apollo Hospitals" },
      { ticker: "DIVISLAB", name: "Divi's Laboratories" },
      { ticker: "CIPLA", name: "Cipla" },
      { ticker: "DRREDDY", name: "Dr. Reddy's" },
      { ticker: "FORTIS", name: "Fortis Healthcare" },
      { ticker: "LALPATHLAB", name: "Dr. Lal PathLabs" },
      { ticker: "METROPOLIS", name: "Metropolis" },
      { ticker: "SYNGENE", name: "Syngene" },
    ],
  },
  {
    id: "hospitals",
    label: "Hospitals",
    yahooSymbol: "NIFTY_HOSPITALS.NS",
    stocks: [
      { ticker: "APOLLOHOSP", name: "Apollo Hospitals" },
      { ticker: "MAXHEALTH", name: "Max Healthcare" },
      { ticker: "FORTIS", name: "Fortis Healthcare" },
      { ticker: "MEDANTA", name: "Medanta" },
      { ticker: "NH", name: "Narayana Hrudayalaya" },
      { ticker: "KIMS", name: "KIMS Hospitals" },
      { ticker: "RAINBOW", name: "Rainbow Children's" },
      { ticker: "ASTERDM", name: "Aster DM Healthcare" },
      { ticker: "HCG", name: "HealthCare Global" },
      { ticker: "JLHL", name: "Jupiter Life Line" },
    ],
  },
  {
    id: "consumer-durables",
    label: "Consumer Durables",
    yahooSymbol: "NIFTY_CONSR_DURBL.NS",
    stocks: [
      { ticker: "TITAN", name: "Titan" },
      { ticker: "HAVELLS", name: "Havells" },
      { ticker: "VOLTAS", name: "Voltas" },
      { ticker: "CROMPTON", name: "Crompton Greaves" },
      { ticker: "WHIRLPOOL", name: "Whirlpool" },
      { ticker: "DIXON", name: "Dixon Technologies" },
      { ticker: "KALYANKJIL", name: "Kalyan Jewellers" },
      { ticker: "AMBER", name: "Amber Enterprises" },
      { ticker: "BLUESTARCO", name: "Blue Star" },
      { ticker: "KAJARIACER", name: "Kajaria Ceramics" },
    ],
  },
  {
    id: "retail",
    label: "Retail",
    yahooSymbol: "NIFTY_RETAIL.NS",
    stocks: [
      { ticker: "TRENT", name: "Trent" },
      { ticker: "DMART", name: "Avenue Supermarts" },
      { ticker: "NYKAA", name: "Nykaa" },
      { ticker: "VMM", name: "Vishal Mega Mart" },
      { ticker: "SHOPERSTOP", name: "Shoppers Stop" },
      { ticker: "METROBRAND", name: "Metro Brands" },
      { ticker: "ABFRL", name: "Aditya Birla Fashion" },
      { ticker: "KALYANKJIL", name: "Kalyan Jewellers" },
      { ticker: "TITAN", name: "Titan" },
      { ticker: "VMART", name: "V-Mart" },
    ],
  },
  {
    id: "oil-gas",
    label: "Oil & Gas",
    yahooSymbol: "NIFTY_OIL_AND_GAS.NS",
    stocks: [
      { ticker: "RELIANCE", name: "Reliance Industries" },
      { ticker: "ONGC", name: "ONGC" },
      { ticker: "IOC", name: "Indian Oil" },
      { ticker: "BPCL", name: "BPCL" },
      { ticker: "GAIL", name: "GAIL" },
      { ticker: "HINDPETRO", name: "Hindustan Petroleum" },
      { ticker: "PETRONET", name: "Petronet LNG" },
      { ticker: "OIL", name: "Oil India" },
      { ticker: "IGL", name: "Indraprastha Gas" },
      { ticker: "GUJGASLTD", name: "Gujarat Gas" },
    ],
  },
  {
    id: "telecom",
    label: "Telecom",
    yahooSymbol: "NIFTY_TELECOMMUNICATIONS.NS",
    stocks: [
      { ticker: "BHARTIARTL", name: "Bharti Airtel" },
      { ticker: "INDUSTOWER", name: "Indus Towers" },
      { ticker: "IDEA", name: "Vodafone Idea" },
      { ticker: "TATACOMM", name: "Tata Communications" },
      { ticker: "BHARTIHEXA", name: "Bharti Hexacom" },
      { ticker: "HFCL", name: "HFCL" },
      { ticker: "RAILTEL", name: "RailTel" },
      { ticker: "TTML", name: "Tata Teleservices MH" },
    ],
  },
  {
    id: "internet",
    label: "Internet",
    yahooSymbol: "NIFTY_INTERNET.NS",
    stocks: [
      { ticker: "ETERNAL", name: "Eternal (Zomato)" },
      { ticker: "POLICYBZR", name: "PB Fintech" },
      { ticker: "PAYTM", name: "One 97 Communications" },
      { ticker: "NAUKRI", name: "Info Edge" },
      { ticker: "NYKAA", name: "Nykaa" },
      { ticker: "SWIGGY", name: "Swiggy" },
      { ticker: "IRCTC", name: "IRCTC" },
      { ticker: "ANGELONE", name: "Angel One" },
      { ticker: "MOTILALOFS", name: "Motilal Oswal" },
      { ticker: "INDIAMART", name: "IndiaMART" },
      { ticker: "NAZARA", name: "Nazara Technologies" },
      { ticker: "TBOTEK", name: "TBO Tek" },
      { ticker: "CARTRADE", name: "CarTrade" },
      { ticker: "FIRSTCRY", name: "FirstCry" },
      { ticker: "IXIGO", name: "ixigo" },
      { ticker: "JUSTDIAL", name: "Just Dial" },
      { ticker: "INFIBEAM", name: "Infibeam Avenues" },
      { ticker: "IIFLCAPS", name: "IIFL Capital" },
    ],
  },
  {
    id: "digital",
    label: "India Digital",
    yahooSymbol: "NIFTY_IND_DIGITAL.NS",
    stocks: [
      { ticker: "TCS", name: "Tata Consultancy Services" },
      { ticker: "INFY", name: "Infosys" },
      { ticker: "HCLTECH", name: "HCL Technologies" },
      { ticker: "ETERNAL", name: "Eternal (Zomato)" },
      { ticker: "NAUKRI", name: "Info Edge" },
      { ticker: "PAYTM", name: "One 97 Communications" },
      { ticker: "NYKAA", name: "Nykaa" },
      { ticker: "POLICYBZR", name: "PB Fintech" },
      { ticker: "DIXON", name: "Dixon Technologies" },
      { ticker: "PERSISTENT", name: "Persistent Systems" },
    ],
  },
  {
    id: "defence",
    label: "Defence",
    yahooSymbol: "NIFTY_IND_DEFENCE.NS",
    stocks: [
      { ticker: "HAL", name: "Hindustan Aeronautics" },
      { ticker: "BEL", name: "Bharat Electronics" },
      { ticker: "BDL", name: "Bharat Dynamics" },
      { ticker: "MAZDOCK", name: "Mazagon Dock" },
      { ticker: "COCHINSHIP", name: "Cochin Shipyard" },
      { ticker: "GRSE", name: "Garden Reach Shipbuilders" },
      { ticker: "SOLARINDS", name: "Solar Industries" },
      { ticker: "BEML", name: "BEML" },
      { ticker: "DATAPATTNS", name: "Data Patterns" },
      { ticker: "ZENTEC", name: "Zen Technologies" },
    ],
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    yahooSymbol: "NIFTY_INDIA_MFG.NS",
    stocks: [
      { ticker: "RELIANCE", name: "Reliance Industries" },
      { ticker: "TATASTEEL", name: "Tata Steel" },
      { ticker: "SUNPHARMA", name: "Sun Pharma" },
      { ticker: "MARUTI", name: "Maruti Suzuki" },
      { ticker: "M&M", name: "Mahindra & Mahindra" },
      { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
      { ticker: "ULTRACEMCO", name: "UltraTech Cement" },
      { ticker: "JSWSTEEL", name: "JSW Steel" },
      { ticker: "CIPLA", name: "Cipla" },
      { ticker: "DRREDDY", name: "Dr. Reddy's" },
    ],
  },
  {
    id: "consumption",
    label: "Consumption",
    yahooSymbol: "^CNXCONSUM",
    stocks: [
      { ticker: "ITC", name: "ITC" },
      { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
      { ticker: "NESTLEIND", name: "Nestle India" },
      { ticker: "TITAN", name: "Titan" },
      { ticker: "MARUTI", name: "Maruti Suzuki" },
      { ticker: "M&M", name: "Mahindra & Mahindra" },
      { ticker: "ASIANPAINT", name: "Asian Paints" },
      { ticker: "BRITANNIA", name: "Britannia" },
      { ticker: "TRENT", name: "Trent" },
      { ticker: "TATACONSUM", name: "Tata Consumer" },
    ],
  },
  {
    id: "rural",
    label: "Rural",
    yahooSymbol: "NIFTY_RURAL.NS",
    stocks: [
      { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
      { ticker: "ITC", name: "ITC" },
      { ticker: "M&M", name: "Mahindra & Mahindra" },
      { ticker: "TATAMOTORS", name: "Tata Motors" },
      { ticker: "HEROMOTOCO", name: "Hero MotoCorp" },
      { ticker: "BAJAJ-AUTO", name: "Bajaj Auto" },
      { ticker: "NESTLEIND", name: "Nestle India" },
      { ticker: "DABUR", name: "Dabur" },
      { ticker: "MARICO", name: "Marico" },
      { ticker: "CHOLAFIN", name: "Cholamandalam" },
    ],
  },
  {
    id: "noncyc-consumer",
    label: "Non-Cyclical Consumer",
    yahooSymbol: "NIFTY_NONCYC_CONS.NS",
    stocks: [
      { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
      { ticker: "ITC", name: "ITC" },
      { ticker: "NESTLEIND", name: "Nestle India" },
      { ticker: "BRITANNIA", name: "Britannia" },
      { ticker: "TITAN", name: "Titan" },
      { ticker: "ASIANPAINT", name: "Asian Paints" },
      { ticker: "TATACONSUM", name: "Tata Consumer" },
      { ticker: "DABUR", name: "Dabur" },
      { ticker: "GODREJCP", name: "Godrej Consumer" },
      { ticker: "MARICO", name: "Marico" },
    ],
  },
  {
    id: "tourism",
    label: "Tourism",
    yahooSymbol: "NIFTY_IND_TOURISM.NS",
    stocks: [
      { ticker: "INDHOTEL", name: "Indian Hotels" },
      { ticker: "IRCTC", name: "IRCTC" },
      { ticker: "EIHOTEL", name: "EIH" },
      { ticker: "LEMONTREE", name: "Lemon Tree" },
      { ticker: "CHALET", name: "Chalet Hotels" },
      { ticker: "ITCHOTELS", name: "ITC Hotels" },
      { ticker: "TBOTEK", name: "TBO Tek" },
      { ticker: "IXIGO", name: "ixigo" },
      { ticker: "JUNIPER", name: "Juniper Hotels" },
      { ticker: "VENTIVE", name: "Ventive Hospitality" },
    ],
  },
  {
    id: "commodities",
    label: "Commodities",
    yahooSymbol: "^CNXCMDT",
    stocks: [
      { ticker: "RELIANCE", name: "Reliance Industries" },
      { ticker: "TATASTEEL", name: "Tata Steel" },
      { ticker: "ONGC", name: "ONGC" },
      { ticker: "COALINDIA", name: "Coal India" },
      { ticker: "HINDALCO", name: "Hindalco" },
      { ticker: "JSWSTEEL", name: "JSW Steel" },
      { ticker: "NTPC", name: "NTPC" },
      { ticker: "ULTRACEMCO", name: "UltraTech Cement" },
      { ticker: "VEDL", name: "Vedanta" },
      { ticker: "HINDZINC", name: "Hindustan Zinc" },
    ],
  },
  {
    id: "chemicals",
    label: "Chemicals",
    yahooSymbol: "NIFTY_CHEMICALS.NS",
    stocks: [
      { ticker: "PIDILITIND", name: "Pidilite" },
      { ticker: "SRF", name: "SRF" },
      { ticker: "PIIND", name: "PI Industries" },
      { ticker: "DEEPAKNTR", name: "Deepak Nitrite" },
      { ticker: "UPL", name: "UPL" },
      { ticker: "NAVINFLUOR", name: "Navin Fluorine" },
      { ticker: "AARTIIND", name: "Aarti Industries" },
      { ticker: "TATACHEM", name: "Tata Chemicals" },
      { ticker: "FLUOROCHEM", name: "Gujarat Fluorochemicals" },
      { ticker: "ALKYLAMINE", name: "Alkyl Amines" },
    ],
  },
  {
    id: "mobility",
    label: "Mobility",
    yahooSymbol: "NIFTY_MOBILITY.NS",
    stocks: [
      { ticker: "MARUTI", name: "Maruti Suzuki" },
      { ticker: "M&M", name: "Mahindra & Mahindra" },
      { ticker: "TATAMOTORS", name: "Tata Motors" },
      { ticker: "BAJAJ-AUTO", name: "Bajaj Auto" },
      { ticker: "EICHERMOT", name: "Eicher Motors" },
      { ticker: "TVSMOTOR", name: "TVS Motor" },
      { ticker: "HEROMOTOCO", name: "Hero MotoCorp" },
      { ticker: "MOTHERSON", name: "Samvardhana Motherson" },
      { ticker: "BOSCHLTD", name: "Bosch" },
      { ticker: "ASHOKLEY", name: "Ashok Leyland" },
    ],
  },
  {
    id: "ev",
    label: "EV & New Age Auto",
    yahooSymbol: "NIFTY_EV.NS",
    stocks: [
      { ticker: "TATAMOTORS", name: "Tata Motors" },
      { ticker: "M&M", name: "Mahindra & Mahindra" },
      { ticker: "TVSMOTOR", name: "TVS Motor" },
      { ticker: "BAJAJ-AUTO", name: "Bajaj Auto" },
      { ticker: "MOTHERSON", name: "Samvardhana Motherson" },
      { ticker: "UNOMINDA", name: "Uno Minda" },
      { ticker: "EXIDEIND", name: "Exide Industries" },
      { ticker: "ARE&M", name: "Amara Raja Energy" },
      { ticker: "OLECTRA", name: "Olectra Greentech" },
      { ticker: "SONACOMS", name: "Sona Comstar" },
    ],
  },
  {
    id: "logistics",
    label: "Transport & Logistics",
    yahooSymbol: "NIFTY_TRANSPORT.NS",
    stocks: [
      { ticker: "ADANIPORTS", name: "Adani Ports" },
      { ticker: "INDIGO", name: "InterGlobe Aviation" },
      { ticker: "CONCOR", name: "Container Corporation" },
      { ticker: "DELHIVERY", name: "Delhivery" },
      { ticker: "BLUEDART", name: "Blue Dart" },
      { ticker: "GESHIP", name: "Great Eastern Shipping" },
      { ticker: "TCI", name: "Transport Corporation" },
      { ticker: "MAHLOG", name: "Mahindra Logistics" },
      { ticker: "VRLLOG", name: "VRL Logistics" },
      { ticker: "IRCTC", name: "IRCTC" },
    ],
  },
  {
    id: "capital-markets",
    label: "Capital Markets",
    yahooSymbol: "NIFTY_CAPITAL_MKT.NS",
    stocks: [
      { ticker: "HDFCAMC", name: "HDFC AMC" },
      { ticker: "ANGELONE", name: "Angel One" },
      { ticker: "MOTILALOFS", name: "Motilal Oswal" },
      { ticker: "BSE", name: "BSE" },
      { ticker: "CDSL", name: "CDSL" },
      { ticker: "MCX", name: "MCX" },
      { ticker: "360ONE", name: "360 One WAM" },
      { ticker: "NUVAMA", name: "Nuvama" },
      { ticker: "IIFLCAPS", name: "IIFL Capital" },
      { ticker: "NAM-INDIA", name: "Nippon Life AMC" },
    ],
  },
  {
    id: "mnc",
    label: "MNC",
    yahooSymbol: "^CNXMNC",
    stocks: [
      { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
      { ticker: "NESTLEIND", name: "Nestle India" },
      { ticker: "BRITANNIA", name: "Britannia" },
      { ticker: "COLPAL", name: "Colgate-Palmolive" },
      { ticker: "MARUTI", name: "Maruti Suzuki" },
      { ticker: "SIEMENS", name: "Siemens" },
      { ticker: "ABB", name: "ABB India" },
      { ticker: "BOSCHLTD", name: "Bosch" },
      { ticker: "CUMMINSIND", name: "Cummins India" },
      { ticker: "HONAUT", name: "Honeywell Automation" },
    ],
  },
  {
    id: "pse",
    label: "PSE",
    yahooSymbol: "^CNXPSE",
    stocks: [
      { ticker: "ONGC", name: "ONGC" },
      { ticker: "NTPC", name: "NTPC" },
      { ticker: "POWERGRID", name: "Power Grid" },
      { ticker: "COALINDIA", name: "Coal India" },
      { ticker: "BEL", name: "Bharat Electronics" },
      { ticker: "HAL", name: "Hindustan Aeronautics" },
      { ticker: "BPCL", name: "BPCL" },
      { ticker: "IOC", name: "Indian Oil" },
      { ticker: "GAIL", name: "GAIL" },
      { ticker: "NMDC", name: "NMDC" },
    ],
  },
  {
    id: "cpse",
    label: "CPSE",
    yahooSymbol: "NIFTY_CPSE.NS",
    stocks: [
      { ticker: "ONGC", name: "ONGC" },
      { ticker: "NTPC", name: "NTPC" },
      { ticker: "POWERGRID", name: "Power Grid" },
      { ticker: "COALINDIA", name: "Coal India" },
      { ticker: "BEL", name: "Bharat Electronics" },
      { ticker: "BPCL", name: "BPCL" },
      { ticker: "OIL", name: "Oil India" },
      { ticker: "NHPC", name: "NHPC" },
      { ticker: "IRCTC", name: "IRCTC" },
      { ticker: "CONCOR", name: "Container Corporation" },
    ],
  },
  {
    id: "services",
    label: "Services",
    yahooSymbol: "^CNXSERVICE",
    stocks: [
      { ticker: "TCS", name: "Tata Consultancy Services" },
      { ticker: "INFY", name: "Infosys" },
      { ticker: "HDFCBANK", name: "HDFC Bank" },
      { ticker: "ICICIBANK", name: "ICICI Bank" },
      { ticker: "HCLTECH", name: "HCL Technologies" },
      { ticker: "SBIN", name: "State Bank of India" },
      { ticker: "BAJFINANCE", name: "Bajaj Finance" },
      { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank" },
      { ticker: "WIPRO", name: "Wipro" },
      { ticker: "TECHM", name: "Tech Mahindra" },
    ],
  },
  {
    id: "midcap-50",
    label: "Midcap 50",
    yahooSymbol: "^NSEMDCP50",
    stocks: [
      { ticker: "PERSISTENT", name: "Persistent Systems" },
      { ticker: "COFORGE", name: "Coforge" },
      { ticker: "DIXON", name: "Dixon Technologies" },
      { ticker: "POLYCAB", name: "Polycab" },
      { ticker: "MAXHEALTH", name: "Max Healthcare" },
      { ticker: "SUZLON", name: "Suzlon" },
      { ticker: "POLICYBZR", name: "PB Fintech" },
      { ticker: "ASHOKLEY", name: "Ashok Leyland" },
      { ticker: "FEDERALBNK", name: "Federal Bank" },
      { ticker: "VOLTAS", name: "Voltas" },
    ],
  },
  {
    id: "next-50",
    label: "Next 50",
    yahooSymbol: "^NSMIDCP",
    stocks: [
      { ticker: "IOC", name: "Indian Oil" },
      { ticker: "VEDL", name: "Vedanta" },
      { ticker: "DIVISLAB", name: "Divi's Laboratories" },
      { ticker: "TRENT", name: "Trent" },
      { ticker: "ADANIPOWER", name: "Adani Power" },
      { ticker: "CHOLAFIN", name: "Cholamandalam" },
      { ticker: "TVSMOTOR", name: "TVS Motor" },
      { ticker: "DLF", name: "DLF" },
      { ticker: "HAL", name: "Hindustan Aeronautics" },
      { ticker: "BEL", name: "Bharat Electronics" },
      { ticker: "VBL", name: "Varun Beverages" },
      { ticker: "ETERNAL", name: "Eternal (Zomato)" },
    ],
  },
  {
    id: "smallcap-50",
    label: "Smallcap 50",
    yahooSymbol: "NIFTYSMLCAP50.NS",
    stocks: [
      { ticker: "CDSL", name: "CDSL" },
      { ticker: "IEX", name: "Indian Energy Exchange" },
      { ticker: "AMBER", name: "Amber Enterprises" },
      { ticker: "KAYNES", name: "Kaynes Technology" },
      { ticker: "CAMS", name: "Computer Age Management" },
      { ticker: "AFFLE", name: "Affle" },
      { ticker: "PPLPHARMA", name: "Piramal Pharma" },
      { ticker: "NATCOPHARM", name: "Natco Pharma" },
      { ticker: "CYIENT", name: "Cyient" },
      { ticker: "SONATSOFTW", name: "Sonata Software" },
    ],
  },
  {
    id: "midcap-100",
    label: "Midcap 100",
    yahooSymbol: "NIFTY_MIDCAP_100.NS",
    stocks: [
      { ticker: "DIXON", name: "Dixon Technologies" },
      { ticker: "PERSISTENT", name: "Persistent Systems" },
      { ticker: "SUZLON", name: "Suzlon" },
      { ticker: "POLYCAB", name: "Polycab" },
      { ticker: "CUMMINSIND", name: "Cummins India" },
      { ticker: "GODREJPROP", name: "Godrej Properties" },
      { ticker: "ASHOKLEY", name: "Ashok Leyland" },
      { ticker: "FEDERALBNK", name: "Federal Bank" },
      { ticker: "VOLTAS", name: "Voltas" },
      { ticker: "MAXHEALTH", name: "Max Healthcare" },
    ],
  },
  {
    id: "renewables",
    label: "Renewables",
    yahooSymbol: "NIFTY_RENEWABLES.NS",
    stocks: [
      { ticker: "ADANIGREEN", name: "Adani Green" },
      { ticker: "SUZLON", name: "Suzlon" },
      { ticker: "TATAPOWER", name: "Tata Power" },
      { ticker: "JSWENERGY", name: "JSW Energy" },
      { ticker: "NHPC", name: "NHPC" },
      { ticker: "SJVN", name: "SJVN" },
      { ticker: "INOXWIND", name: "Inox Wind" },
      { ticker: "WAAREEENER", name: "Waaree Energies" },
      { ticker: "PREMIERENE", name: "Premier Energies" },
      { ticker: "NTPC", name: "NTPC" },
    ],
  },
  {
    id: "railways",
    label: "Railways",
    yahooSymbol: "NIFTY_RAILWAYS.NS",
    stocks: [
      { ticker: "IRCTC", name: "IRCTC" },
      { ticker: "IRFC", name: "IRFC" },
      { ticker: "RVNL", name: "Rail Vikas Nigam" },
      { ticker: "IRCON", name: "IRCON International" },
      { ticker: "RAILTEL", name: "RailTel" },
      { ticker: "CONCOR", name: "Container Corporation" },
      { ticker: "TITAGARH", name: "Titagarh Rail Systems" },
      { ticker: "BEML", name: "BEML" },
      { ticker: "TEXRAIL", name: "Texmaco Rail" },
      { ticker: "RITES", name: "RITES" },
    ],
  },
  {
    id: "textiles",
    label: "Textiles",
    yahooSymbol: "NIFTY_TEXTILES.NS",
    stocks: [
      { ticker: "PAGEIND", name: "Page Industries" },
      { ticker: "KPRMILL", name: "KPR Mill" },
      { ticker: "WELSPUNLIV", name: "Welspun Living" },
      { ticker: "TRIDENT", name: "Trident" },
      { ticker: "RAYMOND", name: "Raymond" },
      { ticker: "VTL", name: "Vardhman Textiles" },
      { ticker: "ARVIND", name: "Arvind" },
      { ticker: "ABFRL", name: "Aditya Birla Fashion" },
      { ticker: "MANYAVAR", name: "Vedant Fashions" },
      { ticker: "KALAMANDIR", name: "Sai Silks" },
    ],
  },
  {
    id: "fertilizers",
    label: "Fertilizers",
    yahooSymbol: "NIFTY_FERTILIZERS.NS",
    stocks: [
      { ticker: "COROMANDEL", name: "Coromandel International" },
      { ticker: "CHAMBLFERT", name: "Chambal Fertilisers" },
      { ticker: "GSFC", name: "GSFC" },
      { ticker: "GNFC", name: "GNFC" },
      { ticker: "NFL", name: "National Fertilizers" },
      { ticker: "RCF", name: "Rashtriya Chemicals" },
      { ticker: "PARADEEP", name: "Paradeep Phosphates" },
      { ticker: "FACT", name: "FACT" },
      { ticker: "UPL", name: "UPL" },
      { ticker: "PIIND", name: "PI Industries" },
    ],
  },
  {
    id: "paints",
    label: "Paints",
    yahooSymbol: "NIFTY_PAINTS.NS",
    stocks: [
      { ticker: "ASIANPAINT", name: "Asian Paints" },
      { ticker: "BERGEPAINT", name: "Berger Paints" },
      { ticker: "KANSAINER", name: "Kansai Nerolac" },
      { ticker: "INDIGOPNTS", name: "Indigo Paints" },
      { ticker: "SHALPAINTS", name: "Shalimar Paints" },
    ],
  },
  {
    id: "jewellery",
    label: "Jewellery",
    yahooSymbol: "NIFTY_JEWELLERY.NS",
    stocks: [
      { ticker: "TITAN", name: "Titan" },
      { ticker: "KALYANKJIL", name: "Kalyan Jewellers" },
      { ticker: "RAJESHEXPO", name: "Rajesh Exports" },
      { ticker: "SENCO", name: "Senco Gold" },
      { ticker: "THANGAMAYL", name: "Thangamayil Jewellery" },
      { ticker: "SKYGOLD", name: "Sky Gold" },
      { ticker: "PCJEWELLER", name: "PC Jeweller" },
      { ticker: "TBZ", name: "Tribhovandas Bhimji Zaveri" },
    ],
  },
  {
    id: "aviation",
    label: "Aviation",
    yahooSymbol: "NIFTY_AVIATION.NS",
    stocks: [
      { ticker: "INDIGO", name: "InterGlobe Aviation" },
      { ticker: "GMRAIRPORT", name: "GMR Airports" },
      { ticker: "GPPL", name: "Gujarat Pipavav Port" },
      { ticker: "IRCTC", name: "IRCTC" },
      { ticker: "TBOTEK", name: "TBO Tek" },
      { ticker: "IXIGO", name: "ixigo" },
    ],
  },
  {
    id: "gas",
    label: "Gas",
    yahooSymbol: "NIFTY_GAS.NS",
    stocks: [
      { ticker: "GAIL", name: "GAIL" },
      { ticker: "PETRONET", name: "Petronet LNG" },
      { ticker: "IGL", name: "Indraprastha Gas" },
      { ticker: "GUJGASLTD", name: "Gujarat Gas" },
      { ticker: "MGL", name: "Mahanagar Gas" },
      { ticker: "ATGL", name: "Adani Total Gas" },
      { ticker: "GSPL", name: "Gujarat State Petronet" },
      { ticker: "ONGC", name: "ONGC" },
    ],
  },
  {
    id: "reits",
    label: "REITs & InvITs",
    yahooSymbol: "NIFTY_REITS_INVITS.NS",
    stocks: [
      { ticker: "EMBASSY", name: "Embassy Office Parks REIT" },
      { ticker: "MINDSPACE", name: "Mindspace Business Parks" },
      { ticker: "BIRET", name: "Brookfield India REIT" },
      { ticker: "NXST", name: "Nexus Select Trust" },
      { ticker: "INDIGRID", name: "IndiGrid" },
      { ticker: "PGINVIT", name: "PowerGrid InvIT" },
      { ticker: "IRBINVIT", name: "IRB InvIT" },
    ],
  },
  {
    id: "beverages",
    label: "Beverages",
    yahooSymbol: "NIFTY_BEVERAGES.NS",
    stocks: [
      { ticker: "VBL", name: "Varun Beverages" },
      { ticker: "UNITDSPR", name: "United Spirits" },
      { ticker: "UBL", name: "United Breweries" },
      { ticker: "RADICO", name: "Radico Khaitan" },
      { ticker: "CCL", name: "CCL Products" },
      { ticker: "TATACONSUM", name: "Tata Consumer" },
      { ticker: "NESTLEIND", name: "Nestle India" },
    ],
  },
  {
    id: "ems",
    label: "Electronics EMS",
    yahooSymbol: "NIFTY_EMS.NS",
    stocks: [
      { ticker: "DIXON", name: "Dixon Technologies" },
      { ticker: "AMBER", name: "Amber Enterprises" },
      { ticker: "KAYNES", name: "Kaynes Technology" },
      { ticker: "SYRMA", name: "Syrma SGS" },
      { ticker: "PGEL", name: "PG Electroplast" },
      { ticker: "AVALON", name: "Avalon Technologies" },
      { ticker: "CYIENTDLM", name: "Cyient DLM" },
      { ticker: "ELIN", name: "Elin Electronics" },
    ],
  },
];

export function getIndianSector(sectorId: string): IndianSector | undefined {
  return INDIAN_SECTORS.find((sector) => sector.id === sectorId);
}

export function getBenchmarkSector(): IndianSector {
  return INDIAN_SECTORS[0]!;
}

export function getResearchSectors(): IndianSector[] {
  return INDIAN_SECTORS.filter((sector) => !sector.isBenchmark);
}

export function findSectorsForTicker(ticker: string): IndianSector[] {
  const key = normalizeEquityTicker(ticker);
  return getResearchSectors().filter((sector) =>
    sector.stocks.some((stock) => normalizeEquityTicker(stock.ticker) === key)
  );
}

let primarySectorByTicker: Map<string, string> | null = null;

function primarySectorLabelMap() {
  if (primarySectorByTicker) return primarySectorByTicker;
  const map = new Map<string, string>();
  for (const sector of getResearchSectors()) {
    for (const stock of sector.stocks) {
      const key = normalizeEquityTicker(stock.ticker);
      if (key && !map.has(key)) map.set(key, sector.label);
    }
  }
  primarySectorByTicker = map;
  return map;
}

export function findPrimarySectorLabel(ticker: string): string | null {
  return primarySectorLabelMap().get(normalizeEquityTicker(ticker)) ?? null;
}

export function tradingViewSymbolForSectorId(sectorId: string): string | null {
  const sector = getIndianSector(sectorId);
  if (!sector) return null;
  return tradingViewSymbolFromYahoo(sector.yahooSymbol);
}

export function getUniqueIndianStocks(): IndianSectorStock[] {
  const seen = new Set<string>();
  const stocks: IndianSectorStock[] = [];
  for (const sector of INDIAN_SECTORS) {
    for (const stock of sector.stocks) {
      const key = normalizeEquityTicker(stock.ticker);
      if (!key || seen.has(key)) continue;
      seen.add(key);
      stocks.push(stock);
    }
  }
  return stocks;
}

export function findStockInSectors(ticker: string): IndianSectorStock | null {
  const key = normalizeEquityTicker(ticker);
  for (const sector of INDIAN_SECTORS) {
    const match = sector.stocks.find(
      (stock) => normalizeEquityTicker(stock.ticker) === key
    );
    if (match) return match;
  }
  return null;
}
